### ISSUE TITLE
Generic parameters with default values fail because they are placed before generated generic parameters in context selectors

### ISSUE THREAD

**Issue by fan-tom** [shepmaster/snafu#116]
I have a trouble using generic error type with default value, as in snafu-generated context selectors original generic parameters are placed before generated ones and if original generic parameter has default value it triggers compilation error, because defaults must be trailing. Error is very hard to understand as it points to original type where the generic parameter is the only, so is trailing, and you need to know how snafu works to understand what is true cause of that compilation error. I suppose the corresponding source is [https://github.com/shepmaster/snafu/blob/e09e9478bcc37968f711b0d5d22f04ea60963c77/snafu-derive/src/lib.rs#L774](https://github.com/shepmaster/snafu/blob/e09e9478bcc37968f711b0d5d22f04ea60963c77/snafu-derive/src/lib.rs#L774)

**Comment by shepmaster** [comment]
For my own curiosity, is your usage of SNAFU with generic parameters with default types available to view somewhere? I added the generic parameter support mostly "because I could", without a very strong use case (I wanted to store a `&'a str`, really). I'd be interested to learn more about how you are using it!
