### ISSUE TITLE
What's the equivalent of failure::Fail::find_root_cause to get to backtrace?

### ISSUE THREAD

**Issue by ArekPiekarz** [shepmaster/snafu#119]
I wanted to port my code from using [failchain](https://crates.io/crates/failchain), which extends the `failure` crate, to snafu. One of the issues was printing backtrace from the root cause. In failchain/failure I could use:
```rust
fn printBacktrace(error: &dyn failure::Fail)
{
    let rootCause = error.find_root_cause();
    if let Some(backtrace) = rootCause.backtrace() {
        println!("{}", backtrace);
    }
}
```

I tried to transform it into this for snafu:
```rust
fn printBacktrace(error: &dyn std::error::Error)
{
    for entry in error.iter_chain() {
        let entry : &dyn ErrorCompat = entry.into();
        if let Some(backtrace) = entry.backtrace() {
            println!("{}", backtrace);
            break;
        }
    }
}
```
It didn't work because there is no way to cast the standard Error into ErrorCompat. They only way I found was adding `#[snafu(backtrace(delegate))]` to every error variant that contains an inner error and calling `backtrace()` on the top error instead of the root. That seems like unnecessary boilerplate in comparison to other frameworks. Would it be possible to somehow make it easier or do we have to wait until standard Error obtains backtrace functionality?

**Comment by shepmaster** [comment]
One mismatch that I see with your original example code is that it assumes that the root error has a backtrace. This is not true in SNAFU: backtraces are opt-in and any intermediate level may add a backtrace. This allows the error definer to decide if a specific error should contain a backtrace and allows adding a backtrace to errors that otherwise wouldn't have them. This is required for interoperation with underlying errors that do or do not have backtraces.

Once the standard library gains backtraces, then the defaults of this library will switch — any variant with an underlying error will automatically set `backtrace(delegate)`.

As I understand it, failure attempts to pretend that the standard library's `Error` type mostly doesn't exist, replacing it with its own types and traits. SNAFU attempts to interoperate with `std::error::Error`, which does mean there are some rough cases like this for now.

My recommendation would be to use `backtrace(delegate)` for now, as this will simplify your calling code to just `if let Some(bt) = ErrorCompat::backtrace(error)`.

In https://github.com/shepmaster/snafu/issues/110#issuecomment-509261737; @CryZe mentions that they've created an iterator over the causes of an error. I suppose we should also think about creating an iterator over `&dyn ErrorCompat`; with such a tool, you could do your latter case as well.

**Comment by ArekPiekarz** [comment]
Thanks for explanation, indeed I missed that backtrace can be stored above the root source. I'll use delegation for now.
