### ISSUE TITLE
Add a troubleshooting section to the guide with common errors

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/snafu#212]
A common error is attempting to use `MyErrorEnum::Variant` when the context selector `Variant` should be used instead. It's worth documenting this.

Are there any other common issues?

**Comment by 0xpr03** [comment]
Another problem I've got:
I was always using something like `Err(MyError::ResponseLimit { response: result })`. That works well untill you try to emit a leaf error including a backtrace. Then you need `ResponseLimit { response: result }`. But you can't do `return Err(ResponseLimit { response: result });`, because that's not a `MyError`, it also won't work with `return Err(MyError::ResponseLimit(ResponseLimit { response: result }))`.
The fix is to use `return ResponseLimit { response: result }.fail();` and it works magically.

**Comment by redragonx** [comment]
Another problem I found while learning SNAFU is that https://github.com/shepmaster/snafu/blob/2c2e6ea5617be02c06e0a8144a5e391de8cd067e/src/guide/attributes.md#controlling-visibility was nowhere to be found in the main docs.

Everything clicked after I found this guide.

**Comment by shepmaster** [comment]
Using `.into()` inside a context selector causes

```
cannot infer type for type parameter `__T0` declared on the struct ...
```

e.g.

```rust
Foo { message: "hello".into() }.fail()
```
