### ISSUE TITLE
A question about generic

### ISSUE THREAD

**Issue by guotie** [shepmaster/snafu#233]
I have a code snippet as flowing
```rust
    pub async fn request<O, Q, D, E, IE>(
        &self,
        method: Method,
        endpoint: &str,
        params: Option<Q>,
        data: Option<D>,
    ) -> Result<O, E>
    where
        O: DeserializeOwned,
        Q: Serialize,
        D: Serialize,
        E: Error + snafu::ErrorCompat + snafu::IntoError<IE, Source=E>
    {
        let mut req = self
            .client
            .request(method, endpoint)
            .body(body);

       Ok(req
                .send()
                .await
                .context(E)?                    <----- compile error
                .json::<ExResponse<_>>()
                .await
                .context(E)?                    <----- compile error
                .into_result()?)
    }
```

because I want this function can be generic for other modules, so, the E in return is generic type.

I don't know how to fix it.

thanks very much.

**Comment by fan-tom** [comment]
If `req.send().await` has error type `SendError` and `.json::<ExResponse<_>>().await` has error type `JsonError`, you must expose that `E: IntoError<IE, Source=SendError> + IntoError<IE, Source=JsonError>`, but you cannot do it, because you cannot implement given trait (`IntoError<IE>`) for given type (`E`) multiple times. So, you need two different types.

You can accept `E: From<SendError> + From<JsonError>` and just use `?` without `.context`. 

If it is not acceptable, you need to have instances of selectors (of types `E1: IntoError<IE, Source=SendError>` and `E2: IntoError<IE, Source=JsonError>`), by taking them as parameters.

Also, seems strange that you return `Result<O, E>`, given such where clause `E: Error + snafu::ErrorCompat + snafu::IntoError<IE, Source=E>`, you should return `Result<O, IE>`, and `E` by itself is not an `Error`, it is just selector, which, beeing passed to `.context`, produces error type (`IE` in your case).

On the other hand, it seems very strange that you want generic context selectors, because it is you who knows what you function do and how it can fail. Asking caller for error selectors is, as for me, implementation detail leak, because now caller knows that you can fail with sending request and with parsing json, so, when you refactor you code, you may end up with bunch of selectors for different fails. I propose you to fix error type of you function and embed it into upper-level error types, or create `From` instances to convert in into caller's error type.

However, you uncovered interesting possibility of having `Default` impl for context selectors without additional fields, which may be helpful in some cases, maybe.

**Comment by guotie** [comment]
Ok.

I modify the function. Return with generic error is too difficult, return response instead.

Thank you very much.
