### ISSUE TITLE
Crate-level documentation and README should mention that it is about error handling

### ISSUE THREAD

**Issue by vi** [shepmaster/snafu#62]
> Easily assign underlying errors into domain-specific errors while adding context

This phrase is only in Github repository description. It is not obvious what is this library about from looking at README or crate-level doc.

Something like the phrase from Github repository description should be copied to the opt of the doc.

**Comment by shepmaster** [comment]
Keeping those three things in sync is always a pain, thanks for helping me to remember!

> that it is about error handling

So, this is a bit odd, but I've wondered if this crate really is about error **handling**. We don't really **handle** the error, just enhance it to provide more information. Handling an error would be a `match` or `Result::or_else`, etc.

Since I have you here... do you have any ideas for what this would be properly called?

**Comment by vi** [comment]
I assumed "error handling" == "error management" (in library context); crates like quick-error, error-chain, failure.
